name: Build, Push And Release [PROD]

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{ vars.AZURE_APP_NAME }} # set this to your application's name, add it to github variables
  AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # set this to the name of the Azure Webapp Publish Profile, add it to github secrets

  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x' # set this to the node version to use
  BUN_VERSION: '1.0.20' # set this to the bun version to use

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-20.04
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: bun install --pure-lockfile

      - name: Build Package
        run: bun run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: trust-hub
          path: dist

  Deploy:
    permissions:
      contents: none
    runs-on: ubuntu-20.04
    needs: build
    environment:
      name: 'TrustHub-Dev-${{ github.run_number }}'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: trust-hub

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
